/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_commun (void);
GtkWidget* create_window_client (void);
GtkWidget* create_window_agent (void);
GtkWidget* create_window_admin (void);
GtkWidget* create_recherche_hotel1 (void);
GtkWidget* create_recherche_vol1 (void);
GtkWidget* create_recherche_voiture1 (void);
GtkWidget* create_recherche_hotel2 (void);
GtkWidget* create_recherche_vol2 (void);
GtkWidget* create_recherche_voiture2 (void);
