/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *window_commun;
  GtkWidget *window_client;
  GtkWidget *window_agent;
  GtkWidget *window_admin;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window_commun = create_window_commun ();
  gtk_widget_show (window_commun);
  /*window_client = create_window_client ();
  gtk_widget_show (window_client);
  window_agent = create_window_agent ();
  gtk_widget_show (window_agent);
  window_admin = create_window_admin ();
  gtk_widget_show (window_admin);*/

  gtk_main ();
  return 0;
}

